#$ -N Testing
#$ -cwd
#$ -j y
#$ -S /bin/bash
#$ -q benzene.q
#$ -o /home/yul13/tmp/clusteroutput.txt
#$ -e /home/yul13/tmp/clustererror.txt
#$ -p myproject.p

date
echo $HOST
module load gcc
module load ics-default
source /home/yul13/codebase/profile.sh
echo checking current machine
uname -a
which gcc
which python
gcc -v
echo running crick project by Yu
#source /home/yul13/.bash_profile
echo "Testing example hello code"
pwd
python ./hello.py
